spring.application.name=event-ticket-mngmt-system

server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5433/event_ticket_management?options=-c%20timezone=Asia/Kolkata
spring.datasource.username=postgres
spring.datasource.password=changemeinprod!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.output.ansi.enabled=ALWAYS

spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9091/realms/event-ticket-management
